from django.db import models
from django.contrib.auth.models import User

# Create your models here.
def get_file_name(intext,filename):
    ext = filename.split(".")[-1]


class UserDetails1(models.Model):
    application_id = models.CharField(max_length=20)
    full_name = models.CharField(max_length=200,null=True,blank=True)
    father_name = models.CharField(max_length=200,null=True,blank=True)
    mother_name = models.CharField(max_length=200,null=True,blank=True)
    dob = models.DateField(null=True)
    gender = models.CharField(max_length=1,blank=True)
    nation = models.CharField(max_length=10,blank=True)
    category = models.CharField(max_length=10,blank=True)
    phys = models.CharField(max_length=1,blank=True)
    email = models.EmailField(null=True)
    mobile = models.CharField(max_length=12,blank=True)
    perma_addr = models.TextField(max_length=400,blank=True)
    corres_addr = models.TextField(max_length=400,blank=True)
    submitt = models.CharField(max_length=2,default="N")
    user = models.OneToOneField(User)

    def __unicode__(self):
        return self.user.username

    image = models.ImageField(upload_to='images')
    signature = models.ImageField(upload_to='signatures')
    ereceipt = models.CharField(max_length=40)
    dop = models.DateField(null=True)
    std_status = models.CharField(max_length=200,blank=True)
    fin_status = models.CharField(max_length=200,blank=True)
    disc_choice1 = models.CharField(max_length=200,blank=True)
    spec_choice1 = models.CharField(max_length=200,blank=True)
    choice_prg2 = models.CharField(max_length=4,default="No")
    disc_choice2 = models.CharField(max_length=200,blank=True)
    spec_choice2 = models.CharField(max_length=200,blank=True)
    choice_prg3 = models.CharField(max_length=4,default="No")
    disc_choice3 = models.CharField(max_length=200,blank=True)
    spec_choice3 = models.CharField(max_length=200,blank=True)
    gatestatus = models.CharField(max_length=100)
    gate_exam = models.CharField(max_length=30)
    gate_roll=models.CharField(max_length=20,blank=True)
    gate_year=models.CharField(max_length=20,blank=True)
    gate_disc = models.CharField(max_length=20,blank=True)
    gate_rank = models.CharField(max_length=20,blank=True)
    gate_score = models.CharField(max_length=20,blank=True)
    score_card = models.ImageField(upload_to='scores')
    detail_scholar=models.CharField(max_length=300,blank=True)
    quali_degree = models.CharField(max_length=100,blank=True)
    status_deg = models.CharField(max_length=50,blank=True)
    degree_name=models.CharField(max_length=100,blank=True)
    univ_name = models.CharField(max_length=200,blank=True)
    degree_disc=models.CharField(max_length=100,blank=True)
    year_passing = models.CharField(max_length=20,blank=True)
    aggre_per = models.CharField(max_length=20,blank=True)
    inter_cert_name= models.CharField(max_length=200,blank=True)
    inter_board_name= models.CharField(max_length=200,blank=True)
    inter_sub= models.CharField(max_length=200,blank=True)
    inter_year_passing = models.CharField(max_length=20,blank=True)
    inter_aggre_per = models.CharField(max_length=20,blank=True)
    high_cert_name= models.CharField(max_length=200,blank=True)
    high_board_name= models.CharField(max_length=200,blank=True)
    high_sub= models.CharField(max_length=200,blank=True)
    high_year_passing = models.CharField(max_length=20,blank=True)
    high_aggre_per = models.CharField(max_length=20,blank=True)
    work_exp = models.CharField(max_length=4,default="No")
    period_from = models.CharField(max_length=200,blank=True)
    period_to = models.CharField(max_length=200,blank=True)
    work_org = models.CharField(max_length=200,blank=True)
    position = models.CharField(max_length=200,blank=True)
    publica_status = models.CharField(max_length=4,default="No")
    publica = models.CharField(max_length=200,blank=True)
    refree1_name = models.CharField(max_length=200,blank=True)
    refree2_name = models.CharField(max_length=200,blank=True)
    refree1_email = models.CharField(max_length=200,blank=True)
    refree2_email = models.CharField(max_length=200,blank=True)
    saved = models.CharField(max_length=200,blank=True)
    saved2 = models.CharField(max_length=200,blank=True)
    registered = models.CharField(max_length=200,blank=True)


class UserDetails2(models.Model):
    application_id = models.CharField(max_length=20)
    full_name = models.CharField(max_length=200,null=True,blank=True)
    father_name = models.CharField(max_length=200,null=True,blank=True)
    mother_name = models.CharField(max_length=200,null=True,blank=True)
    dob = models.DateField(null=True)
    gender = models.CharField(max_length=1,blank=True)
    nation = models.CharField(max_length=10,blank=True)
    category = models.CharField(max_length=10,blank=True)
    phys = models.CharField(max_length=1,blank=True)
    email = models.EmailField(null=True)
    mobile = models.CharField(max_length=12,blank=True)
    perma_addr = models.TextField(max_length=400,blank=True)
    corres_addr = models.TextField(max_length=400,blank=True)
    submitt = models.CharField(max_length=2,default="N")
    user = models.OneToOneField(User)

    def __unicode__(self):
        return self.user.username

    image = models.ImageField(upload_to='images')
    signature = models.ImageField(upload_to='signatures')
    amt = models.CharField(max_length=20)
    ereceipt = models.CharField(max_length=20)
    dop = models.DateField(null=True)
    sstatus = models.CharField(max_length=50,null=False)
    fstatus = models.CharField(max_length=50,null=False)
    pg_program1 = models.CharField(max_length=20,null=False,blank=False)
    dept1 = models.CharField(max_length=50)
    disc11 = models.CharField(max_length=50)
    disc12 = models.CharField(max_length=50)
    disc13 = models.CharField(max_length=50)
    disc14 = models.CharField(max_length=50)
    pg_program_select1 = models.CharField(max_length=4,default="No")
    pg_program2 = models.CharField(max_length=20)
    dept2 = models.CharField(max_length=50)
    disc21 = models.CharField(max_length=50)
    disc22 = models.CharField(max_length=50)
    disc23 = models.CharField(max_length=50)
    disc24 = models.CharField(max_length=50)
    pg_program_select2 = models.CharField(max_length=4,default="No")
    pg_program3 = models.CharField(max_length=20)
    dept3 = models.CharField(max_length=50)
    disc31 = models.CharField(max_length=50)
    disc32 = models.CharField(max_length=50)
    disc33 = models.CharField(max_length=50)
    disc34 = models.CharField(max_length=50)
    gate_status = models.CharField(max_length=60)
    exam_name = models.CharField(max_length=20)
    exam_roll = models.CharField(max_length=20,blank=True)
    exam_year = models.CharField(max_length=20,blank=True)
    exam_disc = models.CharField(max_length=100,blank=True)
    exam_rank = models.CharField(max_length=20,blank=True)
    exam_score = models.CharField(max_length=20,blank=True)
    score_card = models.ImageField(upload_to='scores')
    sch_details = models.CharField(max_length=300,blank=True)
    degree = models.CharField(max_length=200,blank=True)
    degree_status = models.CharField(max_length=50,blank=True)
    degree_name = models.CharField(max_length=30,blank=True)
    degree_uni = models.CharField(max_length=100,blank=True)
    degree_disc = models.CharField(max_length=60,blank=True)
    degree_year = models.CharField(max_length=20,blank=True)
    degree_score = models.CharField(max_length=20,blank=True)
    inter = models.CharField(max_length=100,blank=True)
    inter_board = models.CharField(max_length=100,blank=True)
    inter_subject = models.CharField(max_length=200,blank=True)
    inter_year = models.CharField(max_length=20,blank=True)
    inter_score = models.CharField(max_length=20,blank=True)
    high = models.CharField(max_length=100,blank=True)
    high_board = models.CharField(max_length=100,blank=True)
    high_subject = models.CharField(max_length=200,blank=True)
    high_year = models.CharField(max_length=20,blank=True)
    high_score = models.CharField(max_length=20,blank=True)
    work_exp = models.CharField(max_length=4,default="no")
    period_from = models.CharField(max_length=30,blank=True)
    period_to = models.CharField(max_length=30,blank=True)
    work_org = models.CharField(max_length=200,blank=True)
    position = models.CharField(max_length=100,blank=True)
    saved = models.CharField(max_length=200,blank=True)
    saved2 = models.CharField(max_length=200,blank=True)
    registered = models.CharField(max_length=200,blank=True)
